### ISSUE TITLE
error: SidebarTabs is not defined

### ISSUE THREAD

**Issue by shillberry** [erniepatenia/speaking-queue#3]
Console Error
```
foundry.js:655 Error: Error thrown in hooked function '' for hook 'ready'. SidebarTabs is not defined
    at Hooks.onError (foundry.js:654:24)
    at #call (foundry.js:636:36)
    at Hooks.callAll (foundry.js:589:17)
    at Game.setupGame (foundry.js:9098:11)
    at async Game._initializeGameView (foundry.js:10432:5)
    at async Game.initialize (foundry.js:8995:5)Caused by: ReferenceError: SidebarTabs is not defined
    at Object.fn (speaking-queue.js:12:5)
    at #call (foundry.js:632:20)
    at Hooks.callAll (foundry.js:589:17)
    at Game.setupGame (foundry.js:9098:11)
    at async Game._initializeGameView (foundry.js:10432:5)
    at async Game.initialize (foundry.js:8995:5)
onError @ foundry.js:655
#call @ foundry.js:636
callAll @ foundry.js:589
setupGame @ foundry.js:9098
await in setupGame
_initializeGameView @ foundry.js:10432
_initializeView @ foundry.js:10408
initialize @ foundry.js:8995
await in initialize
```

**Comment by shillberry** [comment]
SidebarTabs reference in speaking-queue.js

**Comment by shillberry** [comment]
See docs: https://foundryvtt.com/api/classes/client.Sidebar.html
