### ISSUE TITLE
 must provide a menu type that is a FormApplication or ApplicationV2 instance or subclass

### ISSUE THREAD

**Issue by shillberry** [erniepatenia/speaking-queue#6]
```
Error: Error thrown in hooked function '' for hook 'init'. You must provide a menu type that is a FormApplication or ApplicationV2 instance or subclass
    at Hooks.onError (foundry.js:654:24)
    at #call (foundry.js:636:36)
    at Hooks.callAll (foundry.js:589:17)
    at Game.initialize (foundry.js:8980:11)
    at window.addEventListener.once (foundry.js:95974:26)Caused by: Error: You must provide a menu type that is a FormApplication or ApplicationV2 instance or subclass
    at ClientSettings.registerMenu (foundry.js:3315:13)
    at Object.fn (speaking-queue.js:5:19)
    at #call (foundry.js:632:20)
    at Hooks.callAll (foundry.js:589:17)
    at Game.initialize (foundry.js:8980:11)
    at window.addEventListener.once (foundry.js:95974:26)
```

**Comment by shillberry** [comment]
I don't think the pattern is correct.

If you look at the ChatLog doc, it is a SidebarTab type ... 
https://foundryvtt.com/api/classes/client.ChatLog.html

**Comment by shillberry** [comment]
Superseded by ce51f09dee407052c03bbef50183702d6e305889
