### ISSUE TITLE
 ui.sidebar.tabs.set is not a function

### ISSUE THREAD

**Issue by shillberry** [erniepatenia/speaking-queue#7]
```
foundry.js:655 Error: Error thrown in hooked function '' for hook 'ready'. ui.sidebar.tabs.set is not a function
    at Hooks.onError (foundry.js:654:24)
    at #call (foundry.js:636:36)
    at Hooks.callAll (foundry.js:589:17)
    at Game.setupGame (foundry.js:9098:11)
    at async Game._initializeGameView (foundry.js:10432:5)
    at async Game.initialize (foundry.js:8995:5)
Caused by: TypeError: ui.sidebar.tabs.set is not a function
    at Object.fn (speaking-queue.js:4:21)
    at #call (foundry.js:632:20)
    at Hooks.callAll (foundry.js:589:17)
    at Game.setupGame (foundry.js:9098:11)
    at async Game._initializeGameView (foundry.js:10432:5)
    at async Game.initialize (foundry.js:8995:5)
    ```

**Comment by shillberry** [comment]
See https://github.com/erniepatenia/speaking-queue/blob/main/scripts/speaking-queue.js#L4
